services:
  triton_server_vllm:
    image: triton_server_vllm
    build: .
    environment:
      - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/conda/envs/py_3.10/lib/
    env_file:
      - .env
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ipc: host
    group_add:
      - video
    shm_size: 8G
    volumes:
      - ../:/usr/src/app:Z
    ports:
      - "8888:8888"
    command: /usr/src/app/docker/start_services.sh
